// Builds the year-by-year article archive inside #ArchivePage on
// articles.html from /data/json/articles_tag.json, one <a> per article
// pointing at entry.url (/articles/<year>/<slug>/).
//
// That JSON is generated by py/generate_articles_json.py, which scans the
// article folders under /articles. Add a new article
// (articles/<year>/<slug>/index.md) and re-run the script (the GitHub
// Action does this automatically) and the row shows up here.

(async () => {

    const container = document.getElementById("ArchivePage");

    if (!container) {
        return;
    }


    let index;

    try {
        const response = await fetch("/data/json/articles_tag.json");

        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }

        index = await response.json();
    } catch (error) {
        console.error("Error loading article index:", error);
        container.innerHTML =
            "<p>The article archive could not be loaded.</p>";
        return;
    }


    // --------------------------------------------------------
    // Resolve author -> cast profile links (js/author_link.js).
    // Authors with no matching cast member stay plain text.
    // --------------------------------------------------------

    const authorUrls = new Map();

    if (window.AuthorLink) {
        const names = [...new Set(index.map(a => a.author).filter(Boolean))];
        await Promise.all(names.map(async name => {
            const url = await window.AuthorLink.urlFor(name);
            if (url) {
                authorUrls.set(name, url);
            }
        }));
    }


    // --------------------------------------------------------
    // Group articles by year
    // --------------------------------------------------------

    const byYear = new Map();

    for (const article of index) {

        const year = String(article.year || "").trim() || "unknown_year";

        if (!byYear.has(year)) {
            byYear.set(year, []);
        }

        byYear.get(year).push(article);
    }


    // Numeric years, newest first; non-numeric ("unknown_year") last.
    const years = [...byYear.keys()].sort((a, b) => {

        const aNum = /^\d+$/.test(a);
        const bNum = /^\d+$/.test(b);

        if (aNum && bNum) {
            return Number(b) - Number(a);
        }

        if (aNum) return -1;
        if (bNum) return 1;

        return a.localeCompare(b);
    });


    // --------------------------------------------------------
    // Helpers
    // --------------------------------------------------------

    // "2025-06-03" -> "6/3" ; missing / unparseable -> "-"
    function shortDate(dateString) {

        const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(dateString || "");

        if (!match) {
            return "-";
        }

        return `${Number(match[2])}/${Number(match[3])}`;
    }


    function dateValue(dateString) {

        const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(dateString || "");

        if (!match) {
            return Number.POSITIVE_INFINITY;
        }

        return Number(match[1]) * 10000 +
            Number(match[2]) * 100 +
            Number(match[3]);
    }


    // --------------------------------------------------------
    // Render
    // --------------------------------------------------------

    const parts = [];

    for (const year of years) {

        const articles = byYear.get(year).slice();

        // Oldest first within a year (matches the previous archive).
        // Undated articles fall to the bottom of their group.
        articles.sort((a, b) => dateValue(a.date) - dateValue(b.date));

        const heading = /^\d+$/.test(year) ? year : "Year unknown";

        parts.push(`<h1>${escapeHtml(heading)}</h1>`);
        parts.push("<table>");

        for (const article of articles) {

            const authorName = article.author || "";
            const authorUrl = authorUrls.get(authorName);
            const authorCell = authorUrl
                ? `<a href="${escapeAttr(authorUrl)}">${escapeHtml(authorName)}</a>`
                : escapeHtml(authorName);

            parts.push(
                "<tr>" +
                    `<td class="archive-date">${escapeHtml(shortDate(article.date))}</td>` +
                    '<td class="archive-title">' +
                        `<a href="${escapeAttr(article.url)}">${escapeHtml(article.title || article.slug)}</a>` +
                    "</td>" +
                    `<td class="archive-title">${authorCell}</td>` +
                "</tr>"
            );
        }

        parts.push("</table>");
    }

    container.innerHTML = parts.join("\n");


    // --------------------------------------------------------
    // Escaping
    // --------------------------------------------------------

    function escapeHtml(value) {
        return String(value)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;");
    }

    function escapeAttr(value) {
        return escapeHtml(value).replace(/"/g, "&quot;");
    }
})();
