// Fills the "There are currently N art images, N comics, N articles ..."
// line on index.html (#SiteStats) from the data manifests, so the counts
// track the actual content with no hand-editing.
//
//   art images -> /data/json/artwork.json      one entry per image under
//                 images/artwork/ (generated by py/gen.py)
//   comics     -> /data/json/comic.json         one entry per comic
//   articles   -> /data/json/articles_tag.json  one entry per article
//                 (generated by py/generate_articles_json.py)
//
// Each source is a JSON array, so the count is just its length. If a
// fetch fails the span keeps its fallback text ("many").

(async () => {

    const container = document.getElementById("SiteStats");

    if (!container) {
        return;
    }

    const sources = {
        art: "/data/json/artwork.json",
        comics: "/data/json/comic.json",
        articles: "/data/json/articles_tag.json"
    };

    await Promise.all(
        Object.entries(sources).map(async ([key, url]) => {

            const target =
                container.querySelector(`[data-stat="${key}"]`);

            if (!target) {
                return;
            }

            try {
                const response = await fetch(url);

                if (!response.ok) {
                    throw new Error(`HTTP ${response.status}`);
                }

                const data = await response.json();

                if (Array.isArray(data)) {
                    target.textContent = data.length.toLocaleString();
                }
            } catch (error) {
                console.error(`Could not count ${key}:`, error);
                // Leave the fallback text already in the span.
            }
        })
    );
})();
